export type HolidayType = 'festival' | 'national' | 'cultural' | 'observance';

export interface HolidayEvent {
  id: string;
  name: string;
  date: string; // YYYY-MM-DD
  type: HolidayType;
  emoji: string;
  categoryName: string;
  description: string;
  traditions?: string;
  greeting?: string;
  regions?: string[];
  color?: {
    bg: string;
    text: string;
    border: string;
    dot: string;
  };
}

// Fixed-day annual holidays (Month is 1-indexed, day is 1-31)
interface AnnualFixedEvent {
  id: string;
  month: number;
  day: number;
  name: string;
  type: HolidayType;
  emoji: string;
  categoryName: string;
  description: string;
  traditions?: string;
  greeting?: string;
  regions?: string[];
}

const ANNUAL_FIXED_EVENTS: AnnualFixedEvent[] = [
  {
    id: 'new-year-day',
    month: 1,
    day: 1,
    name: "New Year's Day",
    type: 'national',
    emoji: '🎆',
    categoryName: 'Global Celebration',
    description: 'First day of the year in the Gregorian calendar, celebrated worldwide with new beginnings, resolutions, and fireworks.',
    traditions: 'Making resolutions, gathering with family, watching countdown fireworks, ringing bells.',
    greeting: 'Happy New Year! Wishing you joy, peace, and prosperity.',
    regions: ['Global'],
  },
  {
    id: 'pongal-sankranti',
    month: 1,
    day: 14,
    name: 'Makar Sankranti / Pongal',
    type: 'festival',
    emoji: '🪁',
    categoryName: 'Harvest Festival',
    description: 'Ancient harvest festival celebrating the sun’s transit into Capricorn, marked by flying kites and cooking sweet rice pudding.',
    traditions: 'Flying colorful kites, making traditional Pongal or Tilgul sweets, bonfire celebrations.',
    greeting: 'Happy Makar Sankranti and Pongal! May your life be filled with sweetness and soaring joy.',
    regions: ['India', 'South Asia'],
  },
  {
    id: 'india-republic-day',
    month: 1,
    day: 26,
    name: 'Republic Day',
    type: 'national',
    emoji: '🇮🇳',
    categoryName: 'National Holiday',
    description: 'Honors the date on which the Constitution of India came into effect in 1950.',
    traditions: 'Grand military and cultural parades at Kartavya Path, flag hoisting, patriotic songs.',
    greeting: 'Happy Republic Day! Proud to celebrate unity in diversity.',
    regions: ['India'],
  },
  {
    id: 'groundhog-day',
    month: 2,
    day: 2,
    name: 'Groundhog Day',
    type: 'cultural',
    emoji: '🦫',
    categoryName: 'Folklore Tradition',
    description: 'Traditional folklore holiday where a groundhog predicts the arrival of spring based on whether it sees its shadow.',
    traditions: 'Gathering in Punxsutawney to watch Phil make the seasonal weather prediction.',
    greeting: 'Happy Groundhog Day! Here is to an early spring.',
    regions: ['US', 'Canada'],
  },
  {
    id: 'valentines-day',
    month: 2,
    day: 14,
    name: "Valentine's Day",
    type: 'cultural',
    emoji: '💖',
    categoryName: 'Celebration of Love',
    description: 'A global celebration of love, affection, friendship, and romantic appreciation.',
    traditions: 'Exchanging greeting cards, chocolates, flowers, and romantic dinners.',
    greeting: 'Happy Valentine’s Day! Wishing you warmth, kindness, and love.',
    regions: ['Global'],
  },
  {
    id: 'womens-day',
    month: 3,
    day: 8,
    name: "International Women's Day",
    type: 'observance',
    emoji: '👩',
    categoryName: 'Global Observance',
    description: 'Global holiday honoring women’s social, economic, cultural, and political achievements and advocating for equality.',
    traditions: 'Conferences, community awards, sending flowers and appreciation to inspiring women.',
    greeting: 'Happy International Women’s Day! Celebrating the strength and brilliance of women everywhere.',
    regions: ['Global'],
  },
  {
    id: 'pi-day',
    month: 3,
    day: 14,
    name: 'Pi Day (3.14)',
    type: 'observance',
    emoji: '🥧',
    categoryName: 'STEM & Math Day',
    description: 'Annual celebration of the mathematical constant Pi (π ≈ 3.14) and Albert Einstein’s birthday.',
    traditions: 'Eating pie, reciting digits of pi, hosting science trivia and math challenges.',
    greeting: 'Happy Pi Day! May your day be infinitely sweet and circular.',
    regions: ['Global'],
  },
  {
    id: 'st-patricks-day',
    month: 3,
    day: 17,
    name: "St. Patrick's Day",
    type: 'cultural',
    emoji: '☘️',
    categoryName: 'Cultural Festival',
    description: 'Feast day honoring Saint Patrick, celebrating Irish culture, heritage, folklore, and shamrocks.',
    traditions: 'Wearing green clothing, parades, traditional Irish folk music, shamrock decor.',
    greeting: 'Happy St. Patrick’s Day! May luck and laughter follow you today.',
    regions: ['Ireland', 'US', 'Global'],
  },
  {
    id: 'world-health-day',
    month: 4,
    day: 7,
    name: 'World Health Day',
    type: 'observance',
    emoji: '🩺',
    categoryName: 'Global Observance',
    description: 'Global health awareness day founded under the sponsorship of the World Health Organization (WHO).',
    traditions: 'Health screenings, wellness workshops, mindfulness sessions, community fitness walks.',
    greeting: 'Happy World Health Day! Prioritize your physical and mental wellbeing.',
    regions: ['Global'],
  },
  {
    id: 'songkran',
    month: 4,
    day: 13,
    name: 'Songkran (Thai Water Festival)',
    type: 'festival',
    emoji: '💦',
    categoryName: 'New Year Festival',
    description: 'The traditional Thai New Year celebration famously celebrated with nationwide, joyful water splashing to wash away bad fortune.',
    traditions: 'Water blessing rituals, cleaning temples, family reunions, street water fights.',
    greeting: 'Sawasdee Pee Mai! Happy Songkran to you and your family.',
    regions: ['Thailand', 'Southeast Asia'],
  },
  {
    id: 'earth-day',
    month: 4,
    day: 22,
    name: 'Earth Day',
    type: 'observance',
    emoji: '🌍',
    categoryName: 'Environmental Observance',
    description: 'Global event demonstrating support for environmental protection, conservation, and sustainability.',
    traditions: 'Tree planting, beach cleanups, recycling initiatives, nature hikes, switching off unneeded power.',
    greeting: 'Happy Earth Day! Let’s care for and protect our shared home.',
    regions: ['Global'],
  },
  {
    id: 'world-book-day',
    month: 4,
    day: 23,
    name: 'World Book Day',
    type: 'observance',
    emoji: '📚',
    categoryName: 'Cultural Observance',
    description: 'UNESCO worldwide celebration promoting reading, publishing, and copyright protection.',
    traditions: 'Book exchanges, reading marathons, gifting roses and favorite novels.',
    greeting: 'Happy World Book Day! Wishing you endless adventures between the pages.',
    regions: ['Global'],
  },
  {
    id: 'may-day',
    month: 5,
    day: 1,
    name: "International Workers' Day",
    type: 'national',
    emoji: '🛠️',
    categoryName: 'Public Observance',
    description: 'Celebration of laborers and the working classes promoted by the international labor movement.',
    traditions: 'Rallies, parades, recognizing worker rights and resting from labor.',
    greeting: 'Happy Workers’ Day! Honoring the hard work and dignity of everyone building our communities.',
    regions: ['Global', 'Europe', 'Asia'],
  },
  {
    id: 'cinco-de-mayo',
    month: 5,
    day: 5,
    name: 'Cinco de Mayo',
    type: 'cultural',
    emoji: '🎉',
    categoryName: 'Cultural Celebration',
    description: 'Commemorates the Mexican Army’s victory over the French Empire at the Battle of Puebla in 1862.',
    traditions: 'Mariachi music, Mexican gastronomy (tacos, guacamole), folklore dancing, parades.',
    greeting: '¡Feliz Cinco de Mayo! Celebrating Mexican culture, cuisine, and heritage.',
    regions: ['Mexico', 'US'],
  },
  {
    id: 'world-environment-day',
    month: 6,
    day: 5,
    name: 'World Environment Day',
    type: 'observance',
    emoji: '🌱',
    categoryName: 'Global Observance',
    description: 'United Nations flagship day for encouraging worldwide awareness and action for the protection of our environment.',
    traditions: 'Environmental campaigns, zero-waste challenges, urban gardening.',
    greeting: 'Happy World Environment Day! Act for our planet’s future.',
    regions: ['Global'],
  },
  {
    id: 'juneteenth',
    month: 6,
    day: 19,
    name: 'Juneteenth National Independence Day',
    type: 'national',
    emoji: '🕊️',
    categoryName: 'Federal Holiday',
    description: 'Commemorates the emancipation of enslaved African Americans in Galveston, Texas in 1865.',
    traditions: 'Community festivals, barbecues, spiritual readings, educational talks, music.',
    greeting: 'Happy Juneteenth! Honoring freedom, resilience, and progress.',
    regions: ['US'],
  },
  {
    id: 'yoga-day',
    month: 6,
    day: 21,
    name: 'International Day of Yoga',
    type: 'observance',
    emoji: '🧘',
    categoryName: 'Wellness Observance',
    description: 'United Nations day celebrating the ancient physical, mental, and spiritual practice of Yoga.',
    traditions: 'Group sunrise yoga sessions, meditation circles, breathwork practices.',
    greeting: 'Happy International Yoga Day! May your body find strength and your mind find tranquility.',
    regions: ['Global'],
  },
  {
    id: 'us-independence-day',
    month: 7,
    day: 4,
    name: 'Independence Day (4th of July)',
    type: 'national',
    emoji: '🎆',
    categoryName: 'Federal Holiday',
    description: 'Celebrates the passage of the Declaration of Independence by the Continental Congress on July 4, 1776.',
    traditions: 'Spectacular fireworks, backyard barbecues, concerts, family picnics, parades.',
    greeting: 'Happy 4th of July! Enjoy the festivities, sparklers, and sunshine.',
    regions: ['US'],
  },
  {
    id: 'friendship-day',
    month: 7,
    day: 30,
    name: 'International Day of Friendship',
    type: 'observance',
    emoji: '🤝',
    categoryName: 'Global Observance',
    description: 'Promotes friendship among peoples, countries, cultures, and individuals to inspire peace and build bridges.',
    traditions: 'Reconnecting with old friends, tying friendship bands, sending heartfelt notes.',
    greeting: 'Happy Friendship Day! Thank you for being a wonderful friend.',
    regions: ['Global'],
  },
  {
    id: 'india-independence-day',
    month: 8,
    day: 15,
    name: 'Independence Day',
    type: 'national',
    emoji: '🇮🇳',
    categoryName: 'National Holiday',
    description: 'Commemorates India’s independence from British rule in 1947.',
    traditions: 'Prime Minister’s address from Red Fort, flag hoisting across schools and offices, patriotic kites.',
    greeting: 'Happy Independence Day! Saluting the freedom and spirit of India.',
    regions: ['India'],
  },
  {
    id: 'world-peace-day',
    month: 9,
    day: 21,
    name: 'International Day of Peace',
    type: 'observance',
    emoji: '🕊️',
    categoryName: 'Global Observance',
    description: 'Dedicated to strengthening the ideals of peace, non-violence, and cease-fire worldwide.',
    traditions: 'Ringing the Peace Bell at UN HQ, a moment of silence at noon, peace concerts.',
    greeting: 'Wishing you a peaceful and harmonious International Day of Peace.',
    regions: ['Global'],
  },
  {
    id: 'gandhi-jayanti',
    month: 10,
    day: 2,
    name: 'Gandhi Jayanti',
    type: 'national',
    emoji: '🕊️',
    categoryName: 'National Holiday',
    description: 'Marks the birthday of Mahatma Gandhi, pioneer of non-violent resistance (Satyagraha), observed as International Day of Non-Violence.',
    traditions: 'Prayer meetings at Raj Ghat, spinning charkha, cleanliness and community service drives.',
    greeting: 'Remembering Mahatma Gandhi on his birth anniversary. Peace, truth, and compassion.',
    regions: ['India', 'Global'],
  },
  {
    id: 'teachers-day',
    month: 10,
    day: 5,
    name: "World Teachers' Day",
    type: 'observance',
    emoji: '🧑‍🏫',
    categoryName: 'Global Observance',
    description: 'Celebrates teachers worldwide and the vital role educators play in transforming lives and society.',
    traditions: 'Honoring educators with thank-you notes, flowers, and student tributes.',
    greeting: 'Happy World Teachers’ Day! Deep gratitude to all mentors and teachers.',
    regions: ['Global'],
  },
  {
    id: 'world-mental-health-day',
    month: 10,
    day: 10,
    name: 'World Mental Health Day',
    type: 'observance',
    emoji: '🧠',
    categoryName: 'Global Observance',
    description: 'International day for global mental health education, awareness, and advocacy against social stigma.',
    traditions: 'Wearing green ribbons, open discussions on mental wellness, mindful rest and self-care.',
    greeting: 'Happy World Mental Health Day! Remember to be kind to your mind.',
    regions: ['Global'],
  },
  {
    id: 'halloween',
    month: 10,
    day: 31,
    name: 'Halloween',
    type: 'cultural',
    emoji: '🎃',
    categoryName: 'Cultural Festival',
    description: 'Celebration marking the eve of the Western Christian feast of All Hallows’ Day, with costumes, ghost stories, and pumpkins.',
    traditions: 'Trick-or-treating, carving jack-o’-lanterns, wearing spooky costumes, festive parties.',
    greeting: 'Happy Halloween! Have a spooktacular, fun-filled night full of treats.',
    regions: ['US', 'Canada', 'Europe', 'Global'],
  },
  {
    id: 'dia-de-muertos',
    month: 11,
    day: 1,
    name: 'Día de los Muertos (Day of the Dead)',
    type: 'cultural',
    emoji: '💀',
    categoryName: 'Cultural Festival',
    description: 'Mexican holiday where families welcome back the souls of their deceased relatives for a brief reunion.',
    traditions: 'Building colorful ofrendas (altars) with cempasúchil flowers, calaveras (sugar skulls), and pan de muerto.',
    greeting: '¡Feliz Día de los Muertos! Remembering and honoring loved ones with joy and color.',
    regions: ['Mexico', 'Latin America', 'Global'],
  },
  {
    id: 'veterans-day',
    month: 11,
    day: 11,
    name: 'Veterans Day / Remembrance Day',
    type: 'national',
    emoji: '🎖️',
    categoryName: 'Federal Holiday',
    description: 'Honors military veterans who have served in the United States Armed Forces (also Armistice / Remembrance Day).',
    traditions: 'Two minutes of silence at 11:00 AM, ceremonies at national cemeteries, wearing red poppies.',
    greeting: 'Honoring and thanking all veterans for their dedicated service and sacrifice.',
    regions: ['US', 'UK', 'Commonwealth'],
  },
  {
    id: 'childrens-day',
    month: 11,
    day: 14,
    name: "Children's Day (Bal Diwas)",
    type: 'cultural',
    emoji: '🎈',
    categoryName: 'Celebration Day',
    description: 'Celebrates the rights, welfare, and joyful curiosity of children (in India, commemorates Jawaharlal Nehru’s birth).',
    traditions: 'Fun school activities, magic shows, distribution of sweets and gifts.',
    greeting: 'Happy Children’s Day! Celebrate the wonder, laughter, and imagination of children.',
    regions: ['India', 'Global'],
  },
  {
    id: 'world-aids-day',
    month: 12,
    day: 1,
    name: 'World AIDS Day',
    type: 'observance',
    emoji: '🎗️',
    categoryName: 'Global Observance',
    description: 'Dedicated to raising awareness of the AIDS pandemic caused by the spread of HIV infection.',
    traditions: 'Wearing red ribbons, memorials, educational campaigns, supporting research.',
    greeting: 'Observing World AIDS Day with solidarity, remembrance, and health advocacy.',
    regions: ['Global'],
  },
  {
    id: 'human-rights-day',
    month: 12,
    day: 10,
    name: 'Human Rights Day',
    type: 'observance',
    emoji: '⚖️',
    categoryName: 'Global Observance',
    description: 'Commemorates the day on which the United Nations General Assembly adopted the Universal Declaration of Human Rights in 1948.',
    traditions: 'Conferences, human rights concerts, community dialogues for equality and justice.',
    greeting: 'Happy Human Rights Day! Advocating for universal dignity, freedom, and justice.',
    regions: ['Global'],
  },
  {
    id: 'christmas-eve',
    month: 12,
    day: 24,
    name: 'Christmas Eve',
    type: 'festival',
    emoji: '✨',
    categoryName: 'Festive Holiday',
    description: 'The evening preceding Christmas Day, filled with holiday excitement, midnight mass, and family gatherings.',
    traditions: 'Attending candlelight church services, hanging stockings, leaving milk and cookies for Santa.',
    greeting: 'Merry Christmas Eve! Wishing you a peaceful and magical evening.',
    regions: ['Global'],
  },
  {
    id: 'christmas-day',
    month: 12,
    day: 25,
    name: 'Christmas Day',
    type: 'festival',
    emoji: '🎄',
    categoryName: 'Festive Holiday',
    description: 'Commemorates the birth of Jesus Christ, celebrated globally as a cultural and religious celebration of generosity.',
    traditions: 'Opening gifts around the tree, festive family feasts, singing carols, sharing holiday cheer.',
    greeting: 'Merry Christmas! Wishing you love, joy, and peace this festive season.',
    regions: ['Global'],
  },
  {
    id: 'boxing-day',
    month: 12,
    day: 26,
    name: 'Boxing Day',
    type: 'national',
    emoji: '🎁',
    categoryName: 'Public Holiday',
    description: 'Traditional public holiday celebrated the day after Christmas in Britain, Canada, Australia, and many Commonwealth nations.',
    traditions: 'Giving donations to charitable causes, sports matches (cricket & football), family shopping.',
    greeting: 'Happy Boxing Day! Enjoy unwrapping peace, comfort, and good times.',
    regions: ['UK', 'Canada', 'Australia', 'Commonwealth'],
  },
  {
    id: 'new-years-eve',
    month: 12,
    day: 31,
    name: "New Year's Eve",
    type: 'cultural',
    emoji: '🥂',
    categoryName: 'Global Celebration',
    description: 'The final day of the year, marked by reflection, midnight countdowns, parties, and festive celebrations.',
    traditions: 'Counting down to midnight, toasting with friends, singing Auld Lang Syne, watching ball drops.',
    greeting: 'Happy New Year’s Eve! Here is to concluding the year with gratitude and ringing in great adventures.',
    regions: ['Global'],
  },
];

// Floating / Luni-Solar Festivals & Important Dates for 2024 - 2027
// Key dates accurately mapped across cultures: Hindu, Islamic, Buddhist/Chinese, Jewish, Christian, and US federal rules.
interface FloatingEventEntry {
  id: string;
  year: number;
  date: string; // YYYY-MM-DD
  name: string;
  type: HolidayType;
  emoji: string;
  categoryName: string;
  description: string;
  traditions?: string;
  greeting?: string;
  regions?: string[];
}

const FLOATING_EVENTS: FloatingEventEntry[] = [
  // --- 2024 ---
  {
    id: 'chinese-new-year-2024',
    year: 2024,
    date: '2024-02-10',
    name: 'Chinese / Lunar New Year (Year of the Dragon)',
    type: 'festival',
    emoji: '🐉',
    categoryName: 'Cultural Festival',
    description: 'Grand celebration ushering in the Year of the Wood Dragon, symbolizing power, honor, and fortune.',
    greeting: 'Gong Xi Fa Cai! Happy Lunar New Year!',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'holi-2024',
    year: 2024,
    date: '2024-03-25',
    name: 'Holi (Festival of Colors)',
    type: 'festival',
    emoji: '🎨',
    categoryName: 'Cultural Festival',
    description: 'Ancient Hindu spring festival celebrating the triumph of good over evil with colored powders and water.',
    greeting: 'Bura na mano, Holi hai! Wishing you a vibrant and colorful Holi!',
    regions: ['India', 'Global'],
  },
  {
    id: 'good-friday-2024',
    year: 2024,
    date: '2024-03-29',
    name: 'Good Friday',
    type: 'cultural',
    emoji: '✝️',
    categoryName: 'Religious Holiday',
    description: 'Christian holiday commemorating the crucifixion of Jesus and his death at Calvary.',
    regions: ['Global'],
  },
  {
    id: 'easter-2024',
    year: 2024,
    date: '2024-03-31',
    name: 'Easter Sunday',
    type: 'festival',
    emoji: '🐣',
    categoryName: 'Festive Holiday',
    description: 'Celebrates the resurrection of Jesus Christ from the dead, symbolizing renewal and hope.',
    greeting: 'Happy Easter! Wishing you joy, hope, and new beginnings.',
    regions: ['Global'],
  },
  {
    id: 'eid-fitr-2024',
    year: 2024,
    date: '2024-04-10',
    name: 'Eid al-Fitr',
    type: 'festival',
    emoji: '🌙',
    categoryName: 'Religious Festival',
    description: 'The Festival of Breaking the Fast marking the conclusion of the holy month of Ramadan.',
    greeting: 'Eid Mubarak! May divine blessings bring peace and prosperity.',
    regions: ['Global'],
  },
  {
    id: 'eid-adha-2024',
    year: 2024,
    date: '2024-06-17',
    name: 'Eid al-Adha (Feast of Sacrifice)',
    type: 'festival',
    emoji: '🕌',
    categoryName: 'Religious Festival',
    description: 'Honors the willingness of Ibrahim to sacrifice his son in obedience to God’s command.',
    greeting: 'Eid al-Adha Mubarak! May your sacrifices be rewarded with happiness.',
    regions: ['Global'],
  },
  {
    id: 'diwali-2024',
    year: 2024,
    date: '2024-11-01',
    name: 'Diwali (Festival of Lights)',
    type: 'festival',
    emoji: '🪔',
    categoryName: 'Cultural Festival',
    description: 'The triumph of light over darkness and knowledge over ignorance, celebrated with oil lamps and fireworks.',
    greeting: 'Shubh Deepavali! May your life be illuminated with endless joy.',
    regions: ['India', 'Global'],
  },
  {
    id: 'thanksgiving-2024',
    year: 2024,
    date: '2024-11-28',
    name: 'Thanksgiving',
    type: 'national',
    emoji: '🦃',
    categoryName: 'Federal Holiday',
    description: 'National holiday in the United States celebrating the harvest and blessings of the preceding year.',
    greeting: 'Happy Thanksgiving! Grateful for health, family, and togetherness.',
    regions: ['US'],
  },

  // --- 2025 ---
  {
    id: 'mlk-day-2025',
    year: 2025,
    date: '2025-01-20',
    name: 'Martin Luther King Jr. Day',
    type: 'national',
    emoji: '🕊️',
    categoryName: 'Federal Holiday',
    description: 'Honors civil rights icon Dr. Martin Luther King Jr., promoting service, racial equality, and justice.',
    greeting: 'Honoring the legacy and dream of Dr. Martin Luther King Jr.',
    regions: ['US'],
  },
  {
    id: 'chinese-new-year-2025',
    year: 2025,
    date: '2025-01-29',
    name: 'Chinese / Lunar New Year (Year of the Snake)',
    type: 'festival',
    emoji: '🐍',
    categoryName: 'Cultural Festival',
    description: 'Welcoming the Year of the Wood Snake, celebrated with red lanterns, dragon dances, and reunion dinners.',
    traditions: 'Giving red envelopes (Hongbao), family feasts, lion dance performances.',
    greeting: 'Gong Xi Fa Cai! Happy Lunar New Year filled with wisdom and fortune.',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'lantern-festival-2025',
    year: 2025,
    date: '2025-02-12',
    name: 'Lantern Festival (Yuanxiao)',
    type: 'festival',
    emoji: '🏮',
    categoryName: 'Cultural Festival',
    description: 'Culmination of the 15-day Lunar New Year celebration, releasing glowing lanterns and solving riddles.',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'presidents-day-2025',
    year: 2025,
    date: '2025-02-17',
    name: "Presidents' Day",
    type: 'national',
    emoji: '🏛️',
    categoryName: 'Federal Holiday',
    description: 'Honors George Washington, Abraham Lincoln, and all past US presidents.',
    regions: ['US'],
  },
  {
    id: 'maha-shivaratri-2025',
    year: 2025,
    date: '2025-02-26',
    name: 'Maha Shivaratri',
    type: 'festival',
    emoji: '🔱',
    categoryName: 'Religious Festival',
    description: 'The Great Night of Shiva, symbolizing overcoming darkness and ignorance in life.',
    greeting: 'Har Har Mahadev! Wishing you a blessed Maha Shivaratri.',
    regions: ['India', 'Global'],
  },
  {
    id: 'ramadan-begins-2025',
    year: 2025,
    date: '2025-03-01',
    name: 'Ramadan Begins',
    type: 'observance',
    emoji: '🌙',
    categoryName: 'Holy Month',
    description: 'The beginning of the ninth month of the Islamic calendar, observed by Muslims worldwide as a month of fasting, prayer, and charity.',
    greeting: 'Ramadan Mubarak! May this sacred month bring peace and inner reflection.',
    regions: ['Global'],
  },
  {
    id: 'mardi-gras-2025',
    year: 2025,
    date: '2025-03-04',
    name: 'Mardi Gras / Carnival',
    type: 'cultural',
    emoji: '🎭',
    categoryName: 'Carnival Festival',
    description: 'Fat Tuesday festivities featuring extravagant parades, beads, mask balls, and king cake.',
    greeting: 'Laissez les bons temps rouler! Happy Mardi Gras!',
    regions: ['US', 'Brazil', 'Europe', 'Global'],
  },
  {
    id: 'holi-2025',
    year: 2025,
    date: '2025-03-14',
    name: 'Holi (Festival of Colors)',
    type: 'festival',
    emoji: '🎨',
    categoryName: 'Cultural Festival',
    description: 'Celebration of spring, love, and colorful joy with vibrant gulal powder and community music.',
    traditions: 'Playing with colored powder, sharing Gujiya sweets, dancing to dhol beats.',
    greeting: 'Happy Holi! May your year be painted with happiness, prosperity, and love.',
    regions: ['India', 'Global'],
  },
  {
    id: 'eid-fitr-2025',
    year: 2025,
    date: '2025-03-31',
    name: 'Eid al-Fitr',
    type: 'festival',
    emoji: '🌙',
    categoryName: 'Religious Festival',
    description: 'Joyous holiday marking the conclusion of Ramadan fasting with community prayer and feasts.',
    greeting: 'Eid Mubarak! Wishing you and your loved ones peace and abundance.',
    regions: ['Global'],
  },
  {
    id: 'passover-2025',
    year: 2025,
    date: '2025-04-12',
    name: 'Passover (Pesach)',
    type: 'festival',
    emoji: '🍷',
    categoryName: 'Religious Festival',
    description: 'Jewish holiday commemorating the liberation of the Israelites from Egyptian slavery.',
    greeting: 'Chag Pesach Sameach! Wishing you a joyful and meaningful Passover.',
    regions: ['Global'],
  },
  {
    id: 'good-friday-2025',
    year: 2025,
    date: '2025-04-18',
    name: 'Good Friday',
    type: 'cultural',
    emoji: '✝️',
    categoryName: 'Religious Holiday',
    description: 'Commemoration of the passion and crucifixion of Jesus Christ.',
    regions: ['Global'],
  },
  {
    id: 'easter-2025',
    year: 2025,
    date: '2025-04-20',
    name: 'Easter Sunday',
    type: 'festival',
    emoji: '🐣',
    categoryName: 'Festive Holiday',
    description: 'Joyous Christian festival celebrating the resurrection of Christ, spring renewal, and new life.',
    traditions: 'Easter egg hunts, family brunches, pastel decor, church services.',
    greeting: 'Happy Easter! Wishing you peace, renewal, and bright spring days.',
    regions: ['Global'],
  },
  {
    id: 'mothers-day-2025',
    year: 2025,
    date: '2025-05-11',
    name: "Mother's Day",
    type: 'cultural',
    emoji: '💐',
    categoryName: 'Celebration Day',
    description: 'Honoring mothers, maternal bonds, and the influence of mothers in society.',
    greeting: 'Happy Mother’s Day! Celebrating the unconditional love and strength of mothers everywhere.',
    regions: ['US', 'Global'],
  },
  {
    id: 'memorial-day-2025',
    year: 2025,
    date: '2025-05-26',
    name: 'Memorial Day',
    type: 'national',
    emoji: '🇺🇸',
    categoryName: 'Federal Holiday',
    description: 'Honoring and mourning US military personnel who died while serving in the Armed Forces.',
    greeting: 'Remembering and honoring all fallen heroes with gratitude.',
    regions: ['US'],
  },
  {
    id: 'dragon-boat-2025',
    year: 2025,
    date: '2025-05-31',
    name: 'Dragon Boat Festival (Duanwu)',
    type: 'festival',
    emoji: '🛶',
    categoryName: 'Cultural Festival',
    description: 'Traditional Chinese festival famous for energetic dragon boat racing and eating sticky rice dumplings (zongzi).',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'eid-adha-2025',
    year: 2025,
    date: '2025-06-07',
    name: 'Eid al-Adha (Bakrid)',
    type: 'festival',
    emoji: '🕌',
    categoryName: 'Religious Festival',
    description: 'Feast of the Sacrifice concluding the annual Hajj pilgrimage, with charitable giving and communal banquets.',
    greeting: 'Eid al-Adha Mubarak! May your celebrations be filled with harmony and blessings.',
    regions: ['Global'],
  },
  {
    id: 'fathers-day-2025',
    year: 2025,
    date: '2025-06-15',
    name: "Father's Day",
    type: 'cultural',
    emoji: '👔',
    categoryName: 'Celebration Day',
    description: 'Celebrating fathers, fatherhood, paternal bonds, and their role in our lives.',
    greeting: 'Happy Father’s Day! Honoring the wisdom, support, and guidance of fathers.',
    regions: ['US', 'Global'],
  },
  {
    id: 'raksha-bandhan-2025',
    year: 2025,
    date: '2025-08-09',
    name: 'Raksha Bandhan',
    type: 'festival',
    emoji: '🧵',
    categoryName: 'Cultural Festival',
    description: 'Celebrates the bond of love and protection between brothers and sisters, exchanging sacred threads (rakhi).',
    greeting: 'Happy Raksha Bandhan! Celebrating the timeless bond of sibling love and care.',
    regions: ['India', 'Global'],
  },
  {
    id: 'janmashtami-2025',
    year: 2025,
    date: '2025-08-16',
    name: 'Krishna Janmashtami',
    type: 'festival',
    emoji: '🦚',
    categoryName: 'Religious Festival',
    description: 'Celebrates the birth of Lord Krishna with devotional singing, fasting, and human pyramids (Dahi Handi).',
    greeting: 'Happy Janmashtami! May Lord Krishna shower blessings of joy and devotion.',
    regions: ['India', 'Global'],
  },
  {
    id: 'ganesh-chaturthi-2025',
    year: 2025,
    date: '2025-08-27',
    name: 'Ganesh Chaturthi',
    type: 'festival',
    emoji: '🐘',
    categoryName: 'Cultural Festival',
    description: 'Celebrating the arrival of Lord Ganesha, the remover of obstacles and god of wisdom and new beginnings.',
    traditions: 'Installing Ganesha idols, offering sweet modaks, community pandal visits, music processions.',
    greeting: 'Ganpati Bappa Morya! May Lord Ganesha remove all hurdles and bring prosperity.',
    regions: ['India', 'Global'],
  },
  {
    id: 'labor-day-2025',
    year: 2025,
    date: '2025-09-01',
    name: 'Labor Day',
    type: 'national',
    emoji: '🛠️',
    categoryName: 'Federal Holiday',
    description: 'Honors the American labor movement and the contributions that workers have made to the strength and prosperity of the nation.',
    regions: ['US'],
  },
  {
    id: 'onam-2025',
    year: 2025,
    date: '2025-09-05',
    name: 'Onam (Thiruvonam)',
    type: 'festival',
    emoji: '🌺',
    categoryName: 'Harvest Festival',
    description: 'Annual harvest festival of Kerala celebrating the mythical King Mahabali with floral carpets (Pookkalam) and grand feasts (Onasadya).',
    greeting: 'Happy Onam! May the spirit of prosperity and joy illuminate your home.',
    regions: ['India'],
  },
  {
    id: 'rosh-hashanah-2025',
    year: 2025,
    date: '2025-09-22',
    name: 'Rosh Hashanah',
    type: 'festival',
    emoji: '🍎',
    categoryName: 'Religious Holiday',
    description: 'The Jewish New Year, marked by dipping apples in honey for a sweet new year and sounding the shofar horn.',
    greeting: 'Shanah Tovah U’Metukah! Wishing you a sweet, healthy, and happy new year.',
    regions: ['Global'],
  },
  {
    id: 'navratri-begins-2025',
    year: 2025,
    date: '2025-09-22',
    name: 'Sharad Navratri Begins',
    type: 'festival',
    emoji: '💃',
    categoryName: 'Cultural Festival',
    description: 'Nine nights honoring Goddess Durga in her nine divine forms, celebrated with energetic Garba and Dandiya folk dancing.',
    greeting: 'Happy Navratri! May Goddess Durga bless you with strength, grace, and courage.',
    regions: ['India', 'Global'],
  },
  {
    id: 'yom-kippur-2025',
    year: 2025,
    date: '2025-10-01',
    name: 'Yom Kippur (Day of Atonement)',
    type: 'observance',
    emoji: '🕯️',
    categoryName: 'Religious Holiday',
    description: 'The holiest day in Judaism, centered on atonement, 25-hour fasting, and prayer.',
    greeting: 'Gmar Chatimah Tovah! May you be inscribed for a good year.',
    regions: ['Global'],
  },
  {
    id: 'dussehra-2025',
    year: 2025,
    date: '2025-10-02',
    name: 'Dussehra / Vijayadashami',
    type: 'festival',
    emoji: '🏹',
    categoryName: 'Cultural Festival',
    description: 'Celebrates the victory of Lord Rama over Ravana and Goddess Durga over Mahishasura, symbolizing the triumph of virtue.',
    greeting: 'Happy Dussehra! May righteousness, peace, and victory guide your path.',
    regions: ['India', 'Global'],
  },
  {
    id: 'mid-autumn-2025',
    year: 2025,
    date: '2025-10-06',
    name: 'Mid-Autumn Festival (Moon Festival)',
    type: 'festival',
    emoji: '🥮',
    categoryName: 'Harvest Festival',
    description: 'Traditional harvest festival celebrating the full harvest moon with sweet mooncakes and carrying glowing lanterns.',
    greeting: 'Happy Mid-Autumn Festival! May the round moon bring your family peace and harmony.',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'diwali-2025',
    year: 2025,
    date: '2025-10-20',
    name: 'Diwali (Festival of Lights)',
    type: 'festival',
    emoji: '🪔',
    categoryName: 'Cultural Festival',
    description: 'Celebration of light, hope, and knowledge over darkness, with diya oil lamps, rangoli art, sweets, and sparkles.',
    traditions: 'Lighting clay diyas, making vibrant rangoli, bursting sparklers, exchanging mithai sweets.',
    greeting: 'Happy Diwali! May this festival of lights illuminate your life with joy, health, and wealth.',
    regions: ['India', 'Global'],
  },
  {
    id: 'thanksgiving-2025',
    year: 2025,
    date: '2025-11-27',
    name: 'Thanksgiving',
    type: 'national',
    emoji: '🦃',
    categoryName: 'Federal Holiday',
    description: 'American day of gratitude, family feast with roasted turkey, cranberry sauce, and pumpkin pie.',
    traditions: 'Macy’s parade, football games, family dinner, giving thanks for our blessings.',
    greeting: 'Happy Thanksgiving! Wishing you a bountiful feast and heartfelt moments with family.',
    regions: ['US'],
  },
  {
    id: 'black-friday-2025',
    year: 2025,
    date: '2025-11-28',
    name: 'Black Friday',
    type: 'cultural',
    emoji: '🏷️',
    categoryName: 'Shopping Day',
    description: 'The day following Thanksgiving, kicking off the holiday shopping season with major deals.',
    regions: ['US', 'Global'],
  },
  {
    id: 'cyber-monday-2025',
    year: 2025,
    date: '2025-12-01',
    name: 'Cyber Monday',
    type: 'cultural',
    emoji: '💻',
    categoryName: 'Online Shopping Day',
    description: 'Premier online shopping holiday with e-commerce deals following Thanksgiving weekend.',
    regions: ['Global'],
  },
  {
    id: 'hanukkah-2025',
    year: 2025,
    date: '2025-12-14',
    name: 'Hanukkah Begins',
    type: 'festival',
    emoji: '🕎',
    categoryName: 'Religious Festival',
    description: 'The Jewish eight-day Festival of Lights commemorating the rededication of the Second Temple in Jerusalem.',
    traditions: 'Lighting the nine-branched menorah, playing dreidel, eating sufganiyot (jelly doughnuts) and latkes.',
    greeting: 'Chag Urim Sameach! Happy Hanukkah filled with light and warmth.',
    regions: ['Global'],
  },

  // --- 2026 (CURRENT ACTIVE YEAR) ---
  {
    id: 'mlk-day-2026',
    year: 2026,
    date: '2026-01-19',
    name: 'Martin Luther King Jr. Day',
    type: 'national',
    emoji: '🕊️',
    categoryName: 'Federal Holiday',
    description: 'Honoring Dr. Martin Luther King Jr., his inspiring leadership in civil rights, and dedication to peace.',
    greeting: 'Honoring the legacy of Dr. Martin Luther King Jr.',
    regions: ['US'],
  },
  {
    id: 'maha-shivaratri-2026',
    year: 2026,
    date: '2026-02-15',
    name: 'Maha Shivaratri',
    type: 'festival',
    emoji: '🔱',
    categoryName: 'Religious Festival',
    description: 'Solemn festival dedicated to Lord Shiva, observing all-night vigil, fasting, and meditation.',
    greeting: 'Har Har Mahadev! Wishing you peace and spiritual grace on Maha Shivaratri.',
    regions: ['India', 'Global'],
  },
  {
    id: 'presidents-day-2026',
    year: 2026,
    date: '2026-02-16',
    name: "Presidents' Day",
    type: 'national',
    emoji: '🏛️',
    categoryName: 'Federal Holiday',
    description: 'Federal holiday celebrating George Washington’s birthday and honoring all United States presidents.',
    regions: ['US'],
  },
  {
    id: 'chinese-new-year-2026',
    year: 2026,
    date: '2026-02-17',
    name: 'Chinese / Lunar New Year (Year of the Horse)',
    type: 'festival',
    emoji: '🐎',
    categoryName: 'Cultural Festival',
    description: 'Spring Festival welcoming the dynamic Year of the Fire Horse, representing energy, victory, and momentum.',
    traditions: 'Dragon parades, festive family reunions, red envelopes, fireworks.',
    greeting: 'Gong Xi Fa Cai! May the Year of the Horse bring high spirits and great strides!',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'mardi-gras-2026',
    year: 2026,
    date: '2026-02-17',
    name: 'Mardi Gras / Carnival',
    type: 'cultural',
    emoji: '🎭',
    categoryName: 'Carnival Festival',
    description: 'Vibrant Carnival finale with beads, masquerades, music brass bands, and street celebrations.',
    greeting: 'Happy Mardi Gras! Celebrate the rhythm and spirit of Carnival.',
    regions: ['US', 'Brazil', 'Europe', 'Global'],
  },
  {
    id: 'ramadan-begins-2026',
    year: 2026,
    date: '2026-02-18',
    name: 'Ramadan Begins',
    type: 'observance',
    emoji: '🌙',
    categoryName: 'Holy Month',
    description: 'Sacred month of fasting (sawm), prayer, reflection, and community charity for Muslims worldwide.',
    greeting: 'Ramadan Kareem! May this blessed month bring tranquility and spiritual elevation.',
    regions: ['Global'],
  },
  {
    id: 'lantern-festival-2026',
    year: 2026,
    date: '2026-03-03',
    name: 'Lantern Festival (Yuanxiao)',
    type: 'festival',
    emoji: '🏮',
    categoryName: 'Cultural Festival',
    description: 'Marks the first full moon of the lunar year with illuminated lantern displays and sweet glutinous rice balls.',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'holi-2026',
    year: 2026,
    date: '2026-03-04',
    name: 'Holi (Festival of Colors)',
    type: 'festival',
    emoji: '🎨',
    categoryName: 'Cultural Festival',
    description: 'The exuberant celebration of love, spring, and triumph of good, coloring the world with joy and friendship.',
    traditions: 'Splashing gulal colors, dancing with friends, enjoying sweet gujiyas and thandai.',
    greeting: 'Happy Holi! Wishing you and your family a celebration brimming with laughter and colorful cheer.',
    regions: ['India', 'Global'],
  },
  {
    id: 'eid-fitr-2026',
    year: 2026,
    date: '2026-03-20',
    name: 'Eid al-Fitr',
    type: 'festival',
    emoji: '🌙',
    categoryName: 'Religious Festival',
    description: 'Communal celebration concluding the fast of Ramadan, sharing feasts and gifts of charity (Zakat al-Fitr).',
    greeting: 'Eid Mubarak! May peace, harmony, and joy fill your home and heart.',
    regions: ['Global'],
  },
  {
    id: 'passover-2026',
    year: 2026,
    date: '2026-04-01',
    name: 'Passover (Pesach)',
    type: 'festival',
    emoji: '🍷',
    categoryName: 'Religious Festival',
    description: 'The Jewish Festival of Freedom commemorating the Exodus, observed with a traditional Seder meal.',
    greeting: 'Chag Pesach Sameach! Wishing you freedom and peace.',
    regions: ['Global'],
  },
  {
    id: 'good-friday-2026',
    year: 2026,
    date: '2026-04-03',
    name: 'Good Friday',
    type: 'cultural',
    emoji: '✝️',
    categoryName: 'Religious Holiday',
    description: 'Solemn day commemorating the crucifixion of Jesus Christ.',
    regions: ['Global'],
  },
  {
    id: 'easter-2026',
    year: 2026,
    date: '2026-04-05',
    name: 'Easter Sunday',
    type: 'festival',
    emoji: '🐣',
    categoryName: 'Festive Holiday',
    description: 'Celebration of resurrection and rebirth, marked by joyful family gatherings and Easter egg hunts.',
    traditions: 'Decorating Easter eggs, spring flowers, festive family meals.',
    greeting: 'Happy Easter! May your spring bloom with joy, hope, and new opportunities.',
    regions: ['Global'],
  },
  {
    id: 'mothers-day-2026',
    year: 2026,
    date: '2026-05-10',
    name: "Mother's Day",
    type: 'cultural',
    emoji: '💐',
    categoryName: 'Celebration Day',
    description: 'Honoring mothers, grandmothers, and mother figures with flowers, breakfast in bed, and deep gratitude.',
    greeting: 'Happy Mother’s Day! Thank you for the endless love and dedication you bring.',
    regions: ['US', 'Global'],
  },
  {
    id: 'memorial-day-2026',
    year: 2026,
    date: '2026-05-25',
    name: 'Memorial Day',
    type: 'national',
    emoji: '🇺🇸',
    categoryName: 'Federal Holiday',
    description: 'Honoring fallen service members who gave their lives in defense of freedom.',
    greeting: 'Remembering and honoring our fallen heroes on Memorial Day.',
    regions: ['US'],
  },
  {
    id: 'eid-adha-2026',
    year: 2026,
    date: '2026-05-27',
    name: 'Eid al-Adha (Feast of Sacrifice)',
    type: 'festival',
    emoji: '🕌',
    categoryName: 'Religious Festival',
    description: 'Major Islamic feast honoring devotion, charity, and sharing meals with the less fortunate.',
    greeting: 'Eid al-Adha Mubarak! May your heart and home overflow with grace.',
    regions: ['Global'],
  },
  {
    id: 'dragon-boat-2026',
    year: 2026,
    date: '2026-06-19',
    name: 'Dragon Boat Festival (Duanwu)',
    type: 'festival',
    emoji: '🛶',
    categoryName: 'Cultural Festival',
    description: 'Pounding drumbeats, racing boats with dragon prows, and enjoying fragrant zongzi dumplings.',
    greeting: 'Wishing you health and prosperity on the Dragon Boat Festival.',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'fathers-day-2026',
    year: 2026,
    date: '2026-06-21',
    name: "Father's Day",
    type: 'cultural',
    emoji: '👔',
    categoryName: 'Celebration Day',
    description: 'Celebrating fathers, mentors, and role models with love and appreciation.',
    greeting: 'Happy Father’s Day! Thank you for your guidance, encouragement, and patience.',
    regions: ['US', 'Global'],
  },
  {
    id: 'onam-2026',
    year: 2026,
    date: '2026-08-26',
    name: 'Onam (Thiruvonam)',
    type: 'festival',
    emoji: '🌺',
    categoryName: 'Harvest Festival',
    description: 'Kerala’s beloved harvest celebration with colorful floral pookkalams, pulikali tiger dances, and festive onasadya.',
    greeting: 'Happy Onam! May the spirit of prosperity, togetherness, and happiness bless your home.',
    regions: ['India'],
  },
  {
    id: 'raksha-bandhan-2026',
    year: 2026,
    date: '2026-08-28',
    name: 'Raksha Bandhan',
    type: 'festival',
    emoji: '🧵',
    categoryName: 'Cultural Festival',
    description: 'Celebrates the bond between brothers and sisters, tying protective sacred threads and giving gifts.',
    greeting: 'Happy Raksha Bandhan! Celebrating an unbreakable bond of unconditional love and laughter.',
    regions: ['India', 'Global'],
  },
  {
    id: 'janmashtami-2026',
    year: 2026,
    date: '2026-09-04',
    name: 'Krishna Janmashtami',
    type: 'festival',
    emoji: '🦚',
    categoryName: 'Religious Festival',
    description: 'Celebrating the divine birth of Lord Krishna with devotional bhajans, fasting, and joyous dahi handi festivities.',
    greeting: 'Shubha Janmashtami! May Lord Krishna guide your journey with wisdom and love.',
    regions: ['India', 'Global'],
  },
  {
    id: 'labor-day-2026',
    year: 2026,
    date: '2026-09-07',
    name: 'Labor Day',
    type: 'national',
    emoji: '🛠️',
    categoryName: 'Federal Holiday',
    description: 'National holiday paying tribute to the achievements and dedication of workers across the nation.',
    regions: ['US'],
  },
  {
    id: 'rosh-hashanah-2026',
    year: 2026,
    date: '2026-09-11',
    name: 'Rosh Hashanah',
    type: 'festival',
    emoji: '🍎',
    categoryName: 'Religious Holiday',
    description: 'Welcoming the Jewish year 5787, savoring sweet apples dipped in honey and hearing the shofar call.',
    greeting: 'Shanah Tovah! May this new year be sweet, healthy, and prosperous.',
    regions: ['Global'],
  },
  {
    id: 'ganesh-chaturthi-2026',
    year: 2026,
    date: '2026-09-14',
    name: 'Ganesh Chaturthi',
    type: 'festival',
    emoji: '🐘',
    categoryName: 'Cultural Festival',
    description: 'Welcoming Lord Ganesha, the lord of wisdom, arts, sciences, and new ventures with grand pandals and modaks.',
    greeting: 'Ganpati Bappa Morya! May Lord Ganesha illuminate your endeavors with success.',
    regions: ['India', 'Global'],
  },
  {
    id: 'oktoberfest-2026',
    year: 2026,
    date: '2026-09-19',
    name: 'Oktoberfest Opening Day',
    type: 'cultural',
    emoji: '🥨',
    categoryName: 'Cultural Festival',
    description: 'World’s largest folk festival kickoff in Munich, celebrating Bavarian culture, music, pretzels, and crafts.',
    greeting: 'O’zapft is! Happy Oktoberfest!',
    regions: ['Germany', 'Europe', 'Global'],
  },
  {
    id: 'yom-kippur-2026',
    year: 2026,
    date: '2026-09-21',
    name: 'Yom Kippur (Day of Atonement)',
    type: 'observance',
    emoji: '🕯️',
    categoryName: 'Religious Holiday',
    description: 'Holiest day of reflection, repentance, and prayer in Jewish tradition.',
    greeting: 'Gmar Chatimah Tovah! Wishing you a meaningful day of contemplation.',
    regions: ['Global'],
  },
  {
    id: 'mid-autumn-2026',
    year: 2026,
    date: '2026-09-25',
    name: 'Mid-Autumn Festival (Moon Festival)',
    type: 'festival',
    emoji: '🥮',
    categoryName: 'Harvest Festival',
    description: 'Honoring the brightest harvest moon of the year, sharing sweet lotus-paste mooncakes with family.',
    greeting: 'Happy Mid-Autumn Festival! May the full moon shine good luck upon you.',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'navratri-begins-2026',
    year: 2026,
    date: '2026-10-11',
    name: 'Sharad Navratri Begins',
    type: 'festival',
    emoji: '💃',
    categoryName: 'Cultural Festival',
    description: 'Commencement of the 9 auspicious nights of devotional Garba, Dandiya music, and honoring Shakti.',
    greeting: 'Happy Navratri! May you dance to the beats of happiness and spiritual power.',
    regions: ['India', 'Global'],
  },
  {
    id: 'dussehra-2026',
    year: 2026,
    date: '2026-10-20',
    name: 'Dussehra / Vijayadashami',
    type: 'festival',
    emoji: '🏹',
    categoryName: 'Cultural Festival',
    description: 'Celebrating the victory of good over evil, marking the triumph of Lord Rama and Goddess Durga.',
    greeting: 'Happy Vijayadashami! May every obstacle turn into victory.',
    regions: ['India', 'Global'],
  },
  {
    id: 'diwali-2026',
    year: 2026,
    date: '2026-11-08',
    name: 'Diwali (Festival of Lights)',
    type: 'festival',
    emoji: '🪔',
    categoryName: 'Cultural Festival',
    description: 'The great festival of lights celebrating Lakshmi Puja, welcoming wealth, joy, illumination, and warm sweets.',
    traditions: 'Lighting beautiful diyas, making rangoli patterns, gifting sweets, wearing festive finery.',
    greeting: 'Shubh Deepavali! May this Diwali shower prosperity, light, and good fortune upon your home.',
    regions: ['India', 'Global'],
  },
  {
    id: 'thanksgiving-2026',
    year: 2026,
    date: '2026-11-26',
    name: 'Thanksgiving',
    type: 'national',
    emoji: '🦃',
    categoryName: 'Federal Holiday',
    description: 'American harvest holiday bringing loved ones together around the dinner table in thanksgiving.',
    traditions: 'Sharing what we are grateful for, turkey dinners, pies, parade broadcasts.',
    greeting: 'Happy Thanksgiving! Wishing you a table laden with comfort, laughter, and warm gratitude.',
    regions: ['US'],
  },
  {
    id: 'black-friday-2026',
    year: 2026,
    date: '2026-11-27',
    name: 'Black Friday',
    type: 'cultural',
    emoji: '🏷️',
    categoryName: 'Shopping Day',
    description: 'Epic shopping discounts kicking off the holiday gift season.',
    regions: ['US', 'Global'],
  },
  {
    id: 'cyber-monday-2026',
    year: 2026,
    date: '2026-11-30',
    name: 'Cyber Monday',
    type: 'cultural',
    emoji: '💻',
    categoryName: 'Online Shopping Day',
    description: 'Major online retail event continuing the Thanksgiving shopping weekend.',
    regions: ['Global'],
  },
  {
    id: 'hanukkah-2026',
    year: 2026,
    date: '2026-12-04',
    name: 'Hanukkah Begins',
    type: 'festival',
    emoji: '🕎',
    categoryName: 'Religious Festival',
    description: 'The Festival of Dedication and Lights, lighting candles night by night to commemorate the miracle of oil.',
    greeting: 'Hanukkah Sameach! May the menorah candles bring warmth, light, and peace to your family.',
    regions: ['Global'],
  },

  // --- 2027 ---
  {
    id: 'chinese-new-year-2027',
    year: 2027,
    date: '2027-02-06',
    name: 'Chinese / Lunar New Year (Year of the Goat/Sheep)',
    type: 'festival',
    emoji: '🐐',
    categoryName: 'Cultural Festival',
    description: 'Welcoming the Year of the Fire Goat, representing gentleness, creativity, and harmony.',
    greeting: 'Gong Xi Fa Cai! Happy Lunar New Year!',
    regions: ['Asia', 'Global'],
  },
  {
    id: 'holi-2027',
    year: 2027,
    date: '2027-03-23',
    name: 'Holi (Festival of Colors)',
    type: 'festival',
    emoji: '🎨',
    categoryName: 'Cultural Festival',
    description: 'Spring festival of colors and love, smearing gulal and celebrating unity.',
    greeting: 'Happy Holi! May your days sparkle with joy.',
    regions: ['India', 'Global'],
  },
  {
    id: 'easter-2027',
    year: 2027,
    date: '2027-03-28',
    name: 'Easter Sunday',
    type: 'festival',
    emoji: '🐣',
    categoryName: 'Festive Holiday',
    description: 'Joyful Christian celebration of resurrection and spring hope.',
    greeting: 'Happy Easter! Wishing you peace, renewal, and joy.',
    regions: ['Global'],
  },
  {
    id: 'eid-fitr-2027',
    year: 2027,
    date: '2027-03-10',
    name: 'Eid al-Fitr',
    type: 'festival',
    emoji: '🌙',
    categoryName: 'Religious Festival',
    description: 'Celebration of breaking the fast following the holy month of Ramadan.',
    greeting: 'Eid Mubarak! May blessings shine upon you.',
    regions: ['Global'],
  },
  {
    id: 'diwali-2027',
    year: 2027,
    date: '2027-10-29',
    name: 'Diwali (Festival of Lights)',
    type: 'festival',
    emoji: '🪔',
    categoryName: 'Cultural Festival',
    description: 'Festival of lights celebrating happiness, prosperity, and the triumph of light.',
    greeting: 'Shubh Diwali! Wishing you and your family abundant peace and light.',
    regions: ['India', 'Global'],
  },
  {
    id: 'thanksgiving-2027',
    year: 2027,
    date: '2027-11-25',
    name: 'Thanksgiving',
    type: 'national',
    emoji: '🦃',
    categoryName: 'Federal Holiday',
    description: 'National day of gratitude, feasting, and family togetherness.',
    greeting: 'Happy Thanksgiving!',
    regions: ['US'],
  },
];

// Color theming based on holiday type
export function getHolidayColorTheme(type: HolidayType) {
  switch (type) {
    case 'festival':
      return {
        bg: 'bg-amber-50 dark:bg-amber-950/30',
        text: 'text-amber-900 dark:text-amber-200',
        border: 'border-amber-200 dark:border-amber-800/60',
        pill: 'bg-amber-100 text-amber-900 dark:bg-amber-900/50 dark:text-amber-200 border-amber-300 dark:border-amber-700/50',
        dot: 'bg-amber-500',
      };
    case 'national':
      return {
        bg: 'bg-rose-50 dark:bg-rose-950/30',
        text: 'text-rose-900 dark:text-rose-200',
        border: 'border-rose-200 dark:border-rose-800/60',
        pill: 'bg-rose-100 text-rose-900 dark:bg-rose-900/50 dark:text-rose-200 border-rose-300 dark:border-rose-700/50',
        dot: 'bg-rose-500',
      };
    case 'cultural':
      return {
        bg: 'bg-purple-50 dark:bg-purple-950/30',
        text: 'text-purple-900 dark:text-purple-200',
        border: 'border-purple-200 dark:border-purple-800/60',
        pill: 'bg-purple-100 text-purple-900 dark:bg-purple-900/50 dark:text-purple-200 border-purple-300 dark:border-purple-700/50',
        dot: 'bg-purple-500',
      };
    case 'observance':
    default:
      return {
        bg: 'bg-sky-50 dark:bg-sky-950/30',
        text: 'text-sky-900 dark:text-sky-200',
        border: 'border-sky-200 dark:border-sky-800/60',
        pill: 'bg-sky-100 text-sky-900 dark:bg-sky-900/50 dark:text-sky-200 border-sky-300 dark:border-sky-700/50',
        dot: 'bg-sky-500',
      };
  }
}

/**
 * Generate all events for a given year by combining annual fixed dates and year-specific floating dates.
 */
export function getAllHolidaysForYear(year: number): HolidayEvent[] {
  const list: HolidayEvent[] = [];

  // Add annual fixed events
  for (const item of ANNUAL_FIXED_EVENTS) {
    const monthStr = String(item.month).padStart(2, '0');
    const dayStr = String(item.day).padStart(2, '0');
    const dateStr = `${year}-${monthStr}-${dayStr}`;

    list.push({
      id: `${item.id}-${year}`,
      name: item.name,
      date: dateStr,
      type: item.type,
      emoji: item.emoji,
      categoryName: item.categoryName,
      description: item.description,
      traditions: item.traditions,
      greeting: item.greeting,
      regions: item.regions,
      color: getHolidayColorTheme(item.type),
    });
  }

  // Add year-specific floating events
  const floatings = FLOATING_EVENTS.filter((e) => e.year === year);
  for (const item of floatings) {
    list.push({
      id: item.id,
      name: item.name,
      date: item.date,
      type: item.type,
      emoji: item.emoji,
      categoryName: item.categoryName,
      description: item.description,
      traditions: item.traditions,
      greeting: item.greeting,
      regions: item.regions,
      color: getHolidayColorTheme(item.type),
    });
  }

  // Sort chronologically
  return list.sort((a, b) => a.date.localeCompare(b.date));
}

/**
 * Get holidays for a specific date (YYYY-MM-DD).
 */
export function getHolidaysForDate(dateStr: string): HolidayEvent[] {
  if (!dateStr || dateStr.length < 10) return [];
  const year = parseInt(dateStr.slice(0, 4));
  if (isNaN(year)) return [];

  const all = getAllHolidaysForYear(year);
  return all.filter((h) => h.date === dateStr);
}

/**
 * Get holidays for a specific month (month is 0-indexed, like Date.getMonth()).
 */
export function getHolidaysForMonth(year: number, month: number): HolidayEvent[] {
  const all = getAllHolidaysForYear(year);
  const targetPrefix = `${year}-${String(month + 1).padStart(2, '0')}`;
  return all.filter((h) => h.date.startsWith(targetPrefix));
}

/**
 * Get upcoming holidays from a given reference date.
 */
export function getUpcomingHolidays(fromDateStr: string, limit = 6): HolidayEvent[] {
  const currentYear = parseInt(fromDateStr.slice(0, 4)) || new Date().getFullYear();
  const listThisYear = getAllHolidaysForYear(currentYear);
  const listNextYear = getAllHolidaysForYear(currentYear + 1);

  const combined = [...listThisYear, ...listNextYear];
  const upcoming = combined.filter((h) => h.date >= fromDateStr);
  return upcoming.slice(0, limit);
}

/**
 * Search festivals and holidays by keyword.
 */
export function searchHolidays(query: string, referenceYear = new Date().getFullYear()): HolidayEvent[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];

  const thisYear = getAllHolidaysForYear(referenceYear);
  const nextYear = getAllHolidaysForYear(referenceYear + 1);
  const prevYear = getAllHolidaysForYear(referenceYear - 1);

  const pool = [...prevYear, ...thisYear, ...nextYear];
  return pool.filter(
    (h) =>
      h.name.toLowerCase().includes(q) ||
      h.categoryName.toLowerCase().includes(q) ||
      h.description.toLowerCase().includes(q) ||
      (h.regions && h.regions.some((r) => r.toLowerCase().includes(q)))
  );
}
